title: Peak
email: info@peak-art.org
greeting: Peak
description: > # this means to ignore newlines until another tag
    Art project space and gallery
facebook:  peak.art.92
instagram: peak_london
favicon: favicon.png

emptyArray: []
exclude: [vendor]

# Build settings
paginate: 30
# baseurl: "" # the subpath of your site, e.g. /blog/
baseurl: ""
url: "http://www.peak-art.org" # the base hostname & protocol for your site
highlights: pygments
permalink: posts/:title/
include: ["_pages"]
gems: [jekyll-paginate]
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
    sass_dir: _sass
    style: compressed

# cover images are expected to be 900px by 240px, or at least 15:4 aspect ratio
# thumbnails look best with 3:1 or 5:2 ratios in this layout.
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: "Marilyn Thompson"
            cover: "/media/header.jpg"
            layout: "post"
    -
        scope:
            path: ""
            type: "pages"
        values:
            author: "Marilyn Thompson"
            cover: "/media/header.jpg"
            layout: "default"
