---
title: Peak
email: info@peak-art.org
greeting: Peak
description: |
  Art project space and gallery
facebook: peak.art.92
instagram: peak_london
favicon: favicon.png
emptyArray: []
paginate: 10
baseurl: ''
url: http://localhost
highlights: pygments
permalink: posts/:title/
include:
- _pages
gems:
- jekyll-paginate
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
  sass_dir: _sass
  style: compressed
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    author: Marilyn Thompson
    cover: "/media/header.jpg"
    layout: post
- scope:
    path: ''
    type: pages
  values:
    author: Marilyn Thompson
    cover: "/media/header.jpg"
    layout: default
timezone: Europe/London
